name: CI/CD Pipeline for STM32 (PlatformIO + Clang-Format + Doxygen Verification)

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar PlatformIO
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Paso 3: Instalar dependencias y compilar el proyecto
      - name: Build project
        run: platformio run --project-dir TP_Final/

  check-format:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Verificar formato del código con Clang-Format
      - name: Verify Clang-Format Compliance
        run: |
          sudo apt-get install -y clang-format
          clang-format --style=file --dry-run --Werror TP_Final/src/*.c

  check-doxygen:
    runs-on: ubuntu-latest
  
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
  
      # Paso 2: Instalar Doxygen
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
  
      # Paso 3: Validar comentarios de Doxygen
      - name: Validate Doxygen Comments
        run: |
          doxygen Doxyfile
          grep "warning:.*document" doxygen.log || echo "All elements are properly documented"
        
