name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Instalar dependencias
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential clang-format cmake

    - name: Install Doxygen
      run: sudo apt-get install doxygen
    
    - name: Generate Documentation
      run: doxygen Doxyfile

  lint:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Instalar clang-format
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    # 3. Verificar estilo de código con clang-format
    - name: Check code style
      run: |
        clang-format --dry-run --Werror TP_Final/src/*.c
